data:
  h5_path: /home1/ppatel2025/nowcasting2/data/imerg_data_h5_clean/imerg_data.h5
  patch_dir: /home1/ppatel2025/nowcasting2/nowcaster_models/ldcast/data/IMERG
  cache_dir: /home1/ppatel2025/nowcasting2/nowcaster_models/ldcast/cache
  var_name: IMERG

patches:
  patch_size: 32
  image_size: 64
  stride: 32
  min_nonzeros: 5
  nonzero_threshold: 0.1

pipeline:
  input_timesteps: 16
  output_timesteps: 12
  interval_minutes: 30
  sample_shape: [2, 2]

split:
  chunk_days: 2
  valid_frac: 0.1
  test_frac: 0.1
  random_seed: 42

sampling:
  bins_low: 0.1
  bins_high: 20.0
  num_bins: 10
  batch_size: 32

transform:
  log: true
  threshold: 0.1
  fill_value: 0.01
  mean: -0.1399
  std: 0.4151
